[package]
name = "rust-rookie"
version = "0.1.0"
authors = ["zhiwen <lzw5399@gmail.com>"]
edition = "2018" # rust版本

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
